version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    restart: always
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      PORT: 8000
      CORS_ORIGIN: ${CORS_ORIGIN}
    depends_on:
      - db
  game:
    build:
      context: ./flame_intro
      args:
        API_URL: ${API_URL}
    restart: always
    ports:
      - '80:80'
    depends_on:
      - backend
volumes:
  db_data: 