name: CD – deploy to Azure

on:
  workflow_run:
    workflows: ["Flutter CI"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download tag from CI
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          name: image-tag

      - id: readtag
        run: echo "TAG=$(cat image-tag/tag.txt)" &gt;&gt; $GITHUB_OUTPUT

      - name: Deploy container
        uses: azure/webapps-container-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          images:   ${{ secrets.DOCKERHUB_USERNAME }}/flame-intro:${{ steps.readtag.outputs.TAG }} 